[Github] Update Logs Private Repository Sync Errors
elastic/connectors pull request #2816
Opened 2024-09-11 13:28 UTC by parth-elastic

## Closes https://github.com/elastic/connectors-py/issues/2636

Included rate limit related information in debug logs

## Checklists

#### Pre-Review Checklist
- [x] this PR does NOT contain credentials of any kind, such as API keys or username/passwords (double check `config.yml.example`)
- [x] this PR has a meaningful title
- [x] this PR links to all relevant github issues that it fixes or partially addresses
- [x] if there is no GH issue, please create it. Each PR should have a link to an issue
- [x] this PR has a thorough description
- [x] Covered the changes with automated tests
- [x] Tested the changes locally
- [x] Added a label for each target release version (example: `v7.13.2`, `v7.14.0`, `v8.0.0`)
- [ ] Considered corresponding documentation changes
- [ ] Contributed any configuration settings changes to the configuration reference
- [ ] if you added or changed Rich Configurable Fields for a Native Connector, you made a corresponding PR in [Kibana](https://github.com/elastic/kibana/blob/main/packages/kbn-search-connectors/types/native_connectors.ts)

#### Changes Requiring Extra Attention

- [ ] Security-related changes (encryption, TLS, SSRF, etc)
- [ ] New external service dependencies added.

## Related Pull Requests

## Release Note

2024-09-13 09:11 UTC, artem-shelkovnikov approved these changes

2024-09-13 09:12 UTC, artem-shelkovnikov requested changes
@parth-elastic do you think these logs will be sufficient to investigate the problem?

I'd try to use this branch with the problem that user is having and see if you can debug it. If not, logs should be adjusted.

2024-09-16 13:01 UTC, parth-elastic commented
> @parth-elastic do you think these logs will be sufficient to investigate the problem?

Yes, we tried to cover all the pieces of information required to debug this issue. Since the issue was regarding the rate limit, we've already covered the exceptions and logs related to that.

2025-01-09 16:48 UTC, seanstory approved these changes

2025-03-26 10:20 UTC, jedrazb submitted a review, later dismissed

2025-03-28 09:20 UTC, navarone-feekery approved these changes

2025-03-28 09:34 UTC, merged